### PR TITLE
Add Glance page redirect

### PR DESCRIPTION
**Pull request by floryst**
The repo "paraview-glance" has been renamed to "Glance". In the interest of preserving the old application links, I would like to add these redirects, since the paraview-glance repo no longer exists.

### CODE REVIEW

**Comment by floryst** [comment]
@jcfr @bradking

**Comment by jcfr** [comment]
@floryst  Thank for the contribution

<s>Could you clarify the relationship between https://github.com/Kitware/Glance (formerly `paraview-glance`) and this project ? </s>

Now that the original project is being renamed, it may be a good opportunity to instead work with sysadmin to have `glance.kitware.com` or similar ? See https://github.com/Kitware/Glance/settings/pages

Once this is sorted out,

* updating the README of this project
* and also adding a comment in the publish workflow [^1]

may be sensible.

[^1]: https://github.com/Kitware/Glance/blob/887782691d915a7230692d72174f6940c6fe91f5/.github/workflows/publish.yml#L47-L50

**Comment by floryst** [comment]
> `glance.kitware.com`

That's a good idea. I don't imagine the repo will be renamed anymore, but setting up a custom domain for Glance would be useful in keeping a static URL in the event of a future repo rename. Do we have public repo pages that use a custom domain?

> and also adding a comment in the publish workflow

I should change that publish link, thanks. Github will continue to redirect `paraview-glance` git repo operations to `Glance`, just not pages.

**Comment by floryst** [comment]
> updating the README of this project

Shall I add a section to the root README mentioning that the `paraview-glance` directory is related to the redirects? I already have a README as part of this commit explaining the reasoning. I can make the reasoning clearer if there is ambiguity.

I would prefer this to be merged prior to discussion of the `glance.kitware.com` custom domain, since there are old bookmarks that point to the old URL and I would like to not have those break.

**Comment by jcfr** [comment]
> Do we have public repo pages that use a custom domain?

Here is a recent example I setup, see https://github.com/BrownBiomechanics/autoscoperm.slicer.org

**Comment by jcfr** [comment]
> already have a README as part of this commit explaining the reasoning

I missed that, this is great :+1: 


> I would prefer this to be merged prior to discussion of the glance.kitware.com custom domain, since there are old bookmarks that point to the old URL and I would like to not have those break.

That makes sense. 

In a follow up set of changes, I suggest you look into tweaking the direct so that it first displays a page mentioning the link is obsolete.

This will give the opportunity to whoever has old links to update their bookmarks.

Additionally, it may be worth looking into how this will work with Google crawler to ensure the new domain will be indexed ...

**Comment by floryst** [comment]
> This will give the opportunity to whoever has old links to update their bookmarks.

After giving this some more thought, I think it would make sense to have a timed redirect for the primary page, but not for the app/nightly pages. Reason being is that the main page is a primary point of entry, but for those who have direct bookmarks to the app (via /app or /nightly) probably don't want to see the flash of such a message. That's just how I see this, though I certainly can support adding the timed redirect for the application if my concerns are unfounded.

> Additionally, it may be worth looking into how this will work with Google crawler to ensure the new domain will be indexed ...

The canonical link I specified should help with the indexers realizing that the links should be the new version, but I don't know how best to verify this at the moment.

**Pull request merged**
